### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by me-heer** [rajjaiswal2003/todo-workspace#1]
- [x] Ensure Date is validated before being stored
- [x] Bug: Task missing after a few operations
    - Steps to reproduce:
        - `python main.py add` (create a task)
        - `python main.py add` (create a second task)
        - `python main.py complete` (enter ID: 1, after this step, 1 task remains)
        - `python main.py add` (create third task, after this step, 2 tasks should remain)
        - `python main.py show`
        - Notice how the output of the previous command only shows 1 task instead of 2
- [x] After executing complete or edit command, user should be shown the entire list of tasks before the prompt to select which task to complete or edit
- [x] If user tries to edit a task and provides a task ID which does not exist, the error should be shown directly after user enters task ID (instead of allowing user to enter description and due date, and then later on showing the error)
- [x] Try to implement/maintain a user-friendly counter 
    - While showing the list of tasks to user, they should always see the counters as 1..N
    - Example: When user creates 3 tasks, and removes all 3, the next task added will be shown ID as 4.
    - One way to implement this is: While printing the list of tasks, always start with 1. While printing the list of tasks before editing/completing, print tasks starting with 1, after user enters some value in the prompt, remove the corresponding task from your python dictionary.
- [x] Error handling while trying to complete a task which does not exist. (Try to enter an ID that does not exist after executing the complete command, the execution results in an exception)
- [x] Add requirements.txt file that lists click module as dependency
- [x] Ensure your code has tests which test the code functionality
- [x] Try to setup some sort of linter/formatter

**Comment by rajjaiswal2003** [comment]
ALL ISSUES HAS BEEN RESOLVED
